### PR TITLE
Ft crud bus company

### PR DESCRIPTION
**Pull request by NyiingangoPacifique**
#### What does this PR do?

- Create,Read,Update and Delete Bus and Company

#### Description of Task to be completed?

- An admin or operator must be able to do all CRUD function for Buses and Company and view error or success at any attempt and system should have a skelton.

#### How should this be manually tested?
**First clone this project and**

- checkout on branch

`git checkout origin ft-crud-bus-company`

- next we need to make few change on `.env` if you don't have if you need to create in on project root

1. `REACT_APP_BACKEND_URL=http://phantom-api-pirate.herokuapp.com/
this is backend url
or use  backend port to run it locally which is the only way working now

3. PORT=your_port`

### CODE REVIEW

**Review by Anguandia — CHANGES_REQUESTED** [review]
Good work @NyiingangoPacifique , just a small concern; In bus table, first check if the busses array has any item before you start mapping. Otherwise it will generate an error

**Comment by Anguandia** [comment]
Please rebase with develop and squash commits

**Comment by Anguandia** [comment]
The update method for a bus is errornous
Check the update action and verify

**Review by christianR15c — CHANGES_REQUESTED** [review]
please remove conflicts

**Pull request closed without merging**
